# Generated by Django 5.2.1 on 2025-05-12 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                (
                    "nutri_score",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NutritionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fat_100g", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "saturated_fat_100g",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("trans_fat_100g", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "cholesterol_100g",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("sodium_100g", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "carbohydrates_100g",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("fiber_100g", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sugars_100g", models.DecimalField(decimal_places=2, max_digits=5)),
                ("proteins_100g", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "nutri_score",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "portion_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField()),
                ("calories", models.IntegerField()),
                ("protein", models.FloatField()),
                ("carbs", models.FloatField()),
                ("fat", models.FloatField()),
                ("water", models.FloatField()),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_history",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Nutrition History",
                "ordering": ["-scan_date"],
            },
        ),
    ]
