# Generated by Django 5.2.1 on 2025-05-16 15:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_nutritionhistory_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutritionhistory",
            name="date",
        ),
        migrations.AlterField(
            model_name="nutritionhistory",
            name="scan_date",
            field=models.CharField(
                default=core.models.get_current_datetime, max_length=50
            ),
        ),
    ]
