# Generated by Django 5.2.1 on 2025-05-17 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_nutritionhistory_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutritionhistory",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="nutritionhistory",
            name="carbs",
        ),
        migrations.RemoveField(
            model_name="nutritionhistory",
            name="fat",
        ),
        migrations.RemoveField(
            model_name="nutritionhistory",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="nutritionhistory",
            name="protein",
        ),
        migrations.RemoveField(
            model_name="nutritionhistory",
            name="water",
        ),
    ]
